<a target="_blank" href="https://colab.research.google.com/github/LPolyakova/Linear_Algebra_for_CS_students/blob/main/CP/LA_CP_01_Matrices.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# ЛА-Комп'ютерний практикум-01. Матриці

In [ ]:
# these imports may be useful

import pandas as pd
import numpy as np

 #### Деякі інструменти, які, можливо, стануть у нагоді.

In [ ]:
# these tools may be useful
# give a matrix
a = np.array([[1,2], [2,4], [3,6]]) #3x2 matrix
b = np.array([[1], [2]])            #2x1 matrix = column vector
c = np.array([[1,2], [2,3]])        #2x2 square matrix

#zero matrix
z = np.zeros((2, 3))

#matrix with all 1 elements
ones = np.ones((2,3))

# transpose
at = a.transpose()

# matrix multiplication
prod1 = a @ b
prod2 = np.matmul(a, b)

# dot (inner, scalar) product of vectors
u = np.array([1,2,3])
v = np.array([2,3,4])
uv = np.dot(u, v)

# inverse matrix
c_inv = np.linalg.inv(c)

print(f' zero={z},\n\n all 1-matrix={ones},\n\n a= {a},\n\n b = {b},\n\n,  c= {c}, \n\n a^t = {at},\n\n ab = {prod1}, \n\n ab= {prod2} \n')
print(f'u={u}, v={v}, uv = {uv} \n\n')
print(f'c = {c},\n\n c^(-1) = {c_inv}')

 zero=[[0. 0. 0.]
 [0. 0. 0.]],

 all 1-matrix=[[1. 1. 1.]
 [1. 1. 1.]],

 a= [[1 2]
 [2 4]
 [3 6]],

 b = [[1]
 [2]],

,  c= [[1 2]
 [2 3]],

 a^t = [[1 2 3]
 [2 4 6]],

 ab = [[ 5]
 [10]
 [15]],

 ab= [[ 5]
 [10]
 [15]]

u=[1 2 3], v=[2 3 4], uv = 20


c = [[1 2]
 [2 3]],

 c^(-1) = [[-3.  2.]
 [ 2. -1.]]

💻  **1.1. Перевірка властивостей**

Напишіть функції, які перевіряють чи є квадратна матриця
1) симетричною;
2) верхньотрикутною (нижньотрикутною);
3) діагональною;
4) скалярною

Якщо вам знадобиться порівнювати матриці, то треба використовувати функцію numpy.allclose, а не оператор порівняння $==$. Подумайте чому.

Знайдіть відповідні функції в numpy. Подивіться їх вихідний код та порівняйте з вашим.

In [3]:
#write your code here
import pandas as pd
import numpy as np

def is_symmetric_matrix(arr):
    arr_temp = arr.transpose()
    return np.allclose(arr, arr_temp)


def is_triangular_matrix(arr):
    pass

def is_diagonal_matrix(arr):
    pass

def is_scalar_matrix(arr):
    pass

arr = np.array([
        [1, 0, 1],
        [0, 2, 5],
        [1, 5, 3]
        ])

print(is_symmetric_matrix(arr))

True

💻 **1.2. Діагоналі.**

Напишіть функцію diag\_matrix, яка отримує на вхід натуральне число $n$ і будує матрицю, на діагоналях якої стоять відповідно $0,1,2, \dots n, n-1, \dots 0$ . Наприклад, для $ n = 3 $ будує матрицю
$\left( \begin{array}{cccc} 3 & 2 & 1 & 0 \\ 2 & 3 & 2 & 1 \\ 1 & 2 & 3 & 2 \\ 0 & 1 & 2 & 3 \end{array} \right)$. Використовуйте засоби numpy, не використовуйте цикли та поелементне присвоєння.

In [ ]:
#write your code here

💻 **1.3. Decorate matrix.**

Напишіть функцію decorate\_matrix, яка отримує на вхід матрицю $m\times n$ і ``обходить'' її одиницями. Наприклад, із матриці

$\left( \begin{array}{cc} 3 & 2 \\ 2 & 3 \end{array} \right)$ робить матрицю $\left( \begin{array}{cccc} 1 & 1 & 1 & 1 \\ 1 & 3 & 2 & 1 \\ 1 & 2 & 3 & 1 \\ 1 & 1 & 1 & 1 \end{array} \right)$. Використовуйте засоби numpy, не використовуйте цикли та поелементне присвоєння.

In [ ]:
#write your code here

💻 **1.4. Дії над матрицями.** Проілюструйте властивості матричних операцій, що подано нижче, на декількох прикладах. Матриці для прикладів можете обрати самостійно. Вкажіть у коментарях, які є обмеження на матриці, щоб властивості виконувалися.

1. $(A^t)^t=A$;
2. $(A+B)^t=A^t+B^t$;
3. $(A-B)^t=A^t-B^t$;
4. $(\lambda A)^t=\lambda A^t$;
5. $(AB)^t=B^tA^t$;
6. $(AB)^{-1}=B^{-1}A^{-1}$;
7. $(A^t)^{-1}=(A^{-1})^t$.

In [ ]:
#write your code here

💻 **1.5. pandas - таблиці.** У практичних задачах матриці часто виникають при обробці табличних даних. Ця вправа -- знайомство з python-пакетом pandas, який використовують для роботи з таблицями. Для виконання вправ тримайте під рукою документацію pandas. Ви також можете питати штучний інтелект про потрібні функції, але щоб їх засвоїти, варто писати код самостійно.

1️⃣  Задайте таблицю, в якій будуть дані про деяких людей: Прізвище, Ім'я, Стать, Вік, Зріст, Країна. Подивіться в документації основні способи задання таблиць за допомогою pandas.DataFrame. Проілюструйте їх використання.

In [ ]:
#write your code here

# sample dataframe
data = {'LAST NAME': ['Smith', 'Garcia'],
        'FIRST NAME': ['John', 'Huan'],
        'SEX': ['M', 'M'],
        'AGE' : [34, 70] ,
        'HEIGHT' : [186, 160],
        'COUNTRY' : ['Australia', 'Spain']}

df = pd.DataFrame.from_dict(data)
df

  LAST NAME FIRST NAME SEX  AGE  HEIGHT    COUNTRY
0     Smith       John   M   34     186  Australia
1    Garcia       Huan   M   70     160      Spain

2️⃣  Навчіться виводити
1) перші рядки таблиці (df.head());
2) рядок із вказаним індексом (df.loc[i]);
3) вибірку стовпців (наприклад, 'LAST NAME', 'FIRST NAME', 'COUNTRY')
4) рядки за деякими умовами (наприклад, усіх іспанців, молодших 50 років або усіх жінок, вищіх за 190 см)


Проілюструйте дію функцій прикладами.

3️⃣ Навчиться агрегувати дані за стовпчиками:
1. Знайдіть середній зріст усіх людей;
2. Знайдіть людину(людей) макcимального віку;
3. Знайдіть, скільки представників кожної країни присутні в таблиці (value_counts())

💻 **1.6. Рейтинг.**  У цій задачі ви складете найпростіший рейтинг студентів за допомогою множення матриць. Виконайте наступні кроки:

1️⃣  Складіть таблицю з відомостями про успішність студентів (близько 50 осіб), яка містить  номер залікової книжки студента, прізвище та ім'я, номер групи, оцінки з наступних предметів: Calculus, Algebra, C++ programming, Algorithms, а також відомості про позанавчальну діяльність: Science, Sport, Social. Оцінки з предметів, а також оцінки позанавчальної діяльності студентів мають бути надані за 100-бальною шкалою. Ви можете використати ШІ для створення такої таблиці, знайти готові дані або ж придумати власний спосіб заповнення. Мінімізуйте кількість ручної роботи.

In [ ]:
activity = pd.DataFrame(columns=['ID', 'NAME', 'GROUP', 'CALCULUS', 'ALGEBRA', 'C++', 'ALGORITHMS', 'SCIENCE', 'SPORT', 'SOCIAL'])
activity.loc[0] = {'ID' : "MF_2025_01", 'NAME': "Turing Alan M.", 'GROUP' : "MF11",
                    'CALCULUS' : 70, 'ALGEBRA' : 95, 'C++' : 80, 'ALGORITHMS' : 95, 'SCIENCE' : 100, 'SPORT' : 10, 'SOCIAL' : 0}
activity

,ID,NAME,GROUP,CALCULUS,ALGEBRA,C++,ALGORITHMS,SCIENCE,SPORT,SOCIAL
0,MF_2025_01,Turing Alan M.,MF11,70,95,80,95,100,10,0

2️⃣  Деканат ухвалив рішення, що цього семестру при складанні стипендіального рейтингу найважливіше значення матимуть спеціальні предмети ('C++', 'ALGORITHMS'), а також наукова активність студентів ( 'SCIENCE'), і визначив рейтингові коєфіцієнти: 'CALCULUS' 0.15; 'ALGEBRA' 0.15; 'C++' 0.2; 'ALGORITHMS' 0.2; 'SCIENCE' 0.2; 'SPORT' 0.05, 'SOCIAL' 0.05. Наприклад, підсумковий рейтинг ('SCORE') студента  Turing Alan M. складатиме $0.15\cdot 70+0.15\cdot 95+0.2\cdot 80 +0.2\cdot 95+0.05\cdot 10 + 0.05\cdot 0=80.25$
  
Складіть вектор рейтингових коефіцієнтів $w$ (ваговий вектор). Зробіть виборку з оцінками з таблиці activity і збережіть у вигляді numpy-масиву values.

In [ ]:
#write your code here
#weights vector
# w =

#values matrix
values = np.array(activity[['CALCULUS', 'ALGEBRA', 'C++', 'ALGORITHMS', 'SCIENCE', 'SPORT', 'SOCIAL']])

3️⃣ Обчисліть рейтинги студентів ('SCORE') за допомогою матрично-векторного множення. Додайте стовпчик 'SCORE' до таблиці activity та відсортуйте студентів за цим стовпцем.

In [ ]:
#write your code here

4️⃣ Напишіть функції, які дозволяють за таблицею оцінок і вектором рейтингових коефіцієнтів

 + знаходити рейтинги усіх студентів і виводити його у вигляді таблиці або словника;
 + знаходити рейгинги студентів окремо за групами;
 + знаходити середній бал студентів окремо за предметами, окремо за позанавчальними активностями.

Використайте матрично-векторні вирази.

5️⃣ Протестуйте ваші функції й продемонструйте, як вони працюють. Наприклад, виведіть рейтинги окремо за кожною групою, змінюйте ваговий вектор, нарахуйте за рейтингом стипендію (перші 5% отримують підвищену стипендію, наступні 20% -- звичайну, інші -- не отримують), тощо.

In [ ]:
#write your code here

💻 **1.7. Маркетингова кампанія.** Компанія влаштовує рекламну кампанію своєї продукції. Для цього усіх потенційних клієнтів поділено на $m$ груп (кожна група характеризується спільними характеристиками, наприклад, чоловіки 35-45 років з вищою освітою або жінки-домогосподині віком понад 60, тощо). Компанія замовляє рекламу продукції за $n$ каналами (наприклад, на телебаченні, на веб-сайтах, у відео-блогах, поштою тощо). Здатність каналів забезпечити перегляди потенційних клієнтів характризується $m\times n$ *матрицей охоплення*  $R=(R_{ij})$, де $R_{ij}$ -- це кількість переглядів клієнтів із групи $i$ на кожен долар (або іншу грошову одиницю), витрачений на рекламу в каналі $j$. Наприклад, якщо на рекламу на ТБ-шоу (канал 1) було витрачено 1000 доларів і це шоу подивилось 30 000 домогосподарок пенсійного віку (група 1) і 5 студентів-чоловіків віком до 25 років (група 2), то $R_{11}=30$, $R_{21} = 0.005$.

Нехай вектор $c$ з $n$ компонентами характеризує витрати компанії на рекламу за $n$ каналами, а вектор $v$ з $m$ компонентами характеризує охоплення кожної з $m$ груп клієнтів за всіма каналами реклами, тобто $v_i$ -- це загальна кількість переглядів реклами за всіма каналами клієнтами з групи $i$. Також розглянемо вектор  $a$ з $m$ компонентами, для якого $a_i$ дорівнює доходу (в доларах) на один перегляд реклами клієнтом з групи $i$. Зауважимо, що всі елементи  $R, c, v, a$ є невід'ємними числами.

Задайте власні приклади матриці $R$ і векторів $c, a$. Можете використати штучний інтелект для генерації, або ж вигадати щось своє. Намагайтеся зробити дані реалістичними.

In [ ]:
#write your code here

1️⃣  Розглянемо векторний вираз, за яким можна знайти загальну кількість грошей, що компанія витрачає на рекламу. Це має бути сума усіх компонент вектора $c$. За допомогою матрично-векторного запису цю суму можна подати як $1^t c$, де $1$ -- це вектор з  $n$ компонентами, кожна з яких дорівнює 1, $t$ означає транспонування, тобто $1^t$ -- це вектор-рядок з одиниць.

Обчисліть, скільки ця сума складає у вашому випадку за допомогою отриманого виразу.

In [ ]:
#write your code here

2️⃣  Виразіть вектор $v$ через інші вектори й матриці, задані в задачі. Обчисліть його.

✔️ *Запишіть аналітичний вираз тут*

In [ ]:
#write your code here

3️⃣ Запишіть вираз, за яким можна знайти загальний дохід, що отримає компанія, застосовуючи рекламу. Обчисліть дохід.

✔️ *Запишіть аналітичний вираз тут*

In [ ]:
#write your code here

4️⃣  За матрицею $R$ знайдіть для кожної групи клієнтів той канал, який здійснює найбільше охоплення клієнтів цієї групи (на ньому вигідніше розміщувати рекламу)

In [ ]:
#write your code here